version: "3.8"

networks:
  my_net:
    driver: bridge

services:
  appserver:
    container_name: appserver
    build:
      context: ./app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30ss docker-entrypoint.sh
    tty: true
    ports:
      - "3000:3000"
    networks:
      - my_net
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  nginx:
    container_name: nginxproxy
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - my_net
    depends_on:
      - appserver
  
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=pedro
    ports:
      - '3306:3306'
    volumes:
      - .docker/data:/var/lib/mysql
    networks:
      - my_net
