version: "3.8"

services:
  appserver:
    container_name: appserver
    build:
      context: ./app
    ports:
      - "3000:3000"
  nginx:
    container_name: nginxproxy
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"